### ISSUE TITLE
[Channel Permissions] cases random crashes

### ISSUE THREAD

**Issue by Eden333** [Farcrada/DiscordPlugins#103]
### Describe the bug

It crashes discord

### Expected behavior

Not crash

### To reproduce

I don't know exactly how it's caused because it just happens when I look at my screen and do nothing.

### Screenshots

![image](https://user-images.githubusercontent.com/18154402/182882775-aabe578c-0fb4-4cd8-b7ed-d152a89f5ba3.png)

### OS version

Windows 10 64-Bit (10.0.19044)

### Discord version

Stable 138239 (4ba65c6)

### BetterDiscord version

BetterDiscord 1.5.3-Hotfix2

### Plugin version

4.2.4

**Comment by Farcrada** [comment]
Ah, that's unfortunate. You seem to be on a old version of discord. With `Stable 140355 (cd30e81)` there's a change in Discord.

If you'd like the old version simply grab this one: https://github.com/Farcrada/DiscordPlugins/blob/d62458d86b646a78bd425feba5bb9a4c9eb7cfe7/Channel-Permissions/ChannelPermissions.plugin.js 
And wait until discord crashes again and update to 4.2.4😂
