### ISSUE TITLE
[Right Click Join] The join button is missing

### ISSUE THREAD

**Issue by Sasha98630147** [Farcrada/DiscordPlugins#104]
### Describe the bug

With the new DS update, the join button is gone and only appears if you first open the user profile or click "add note"

### Expected behavior

When you right-click in the list, the item "join" should appear, but it does not.

### OS version

Windows 10

### Discord version

Stable 141635 (01b73aa) 

### BetterDiscord version

BetterDiscord 1.6.2

### Plugin version

1.4.0

**Comment by Farcrada** [comment]
Noted, investigating!
