### ISSUE TITLE
[Spotify to Spotify] Not opened in app

### ISSUE THREAD

**Issue by dankYoff** [Farcrada/DiscordPlugins#105]
### Describe the bug

Firstly opened Spotify in app, but after 1 day it opened via browser

### Expected behavior

Open in app

### To reproduce

1. Open Discord
2. Go to profile
3. Click to Spotify
4. Open Spotify in browser

### Screenshots

![зображення](https://user-images.githubusercontent.com/91318807/190361043-dd0c0104-7a27-40d7-bd0c-b65cb3f694f2.png)
![зображення](https://user-images.githubusercontent.com/91318807/190361094-75d719bb-8379-41a6-9036-85b06a028039.png)
![зображення](https://user-images.githubusercontent.com/91318807/190361114-4fa2445f-deb8-4688-afe3-0bcf4ed1b2a2.png)
![зображення](https://user-images.githubusercontent.com/91318807/190361204-a91e541e-53ec-4c82-976b-897baafed0c9.png)

### OS version

Windows 10 64-Bit (10.0.19044)

### Discord version

147045 (6ba38a9)

### BetterDiscord version

1.6.3

### Plugin version

v1by Farcrada

**Comment by Farcrada** [comment]
Since the updater isn't included in this plugin you'll have to re-download this plugin.

**Comment by dankYoff** [comment]
thank you for your quick response and fix <3
