### ISSUE TITLE
[Double Click To Edit] Trying to open settings results in "There was an unexpected Error. Click to open console for more details."

### ISSUE THREAD

**Issue by nefariouslegion** [Farcrada/DiscordPlugins#107]
### Describe the bug

I downloaded the newest version of Double Click to Edit. When trying to open the settings for the plugin I get this error. 
![image](https://user-images.githubusercontent.com/89366675/192833994-a4ad754a-da74-4171-aaa2-192540029c15.png)

Clicking on it to view the console then shows the following:
![image](https://user-images.githubusercontent.com/89366675/192834108-7c8bc157-a720-42c7-95c0-8e5892ae9780.png)
![image](https://user-images.githubusercontent.com/89366675/192834196-2da2669e-be38-465e-9390-24717aa923e3.png)
![image](https://user-images.githubusercontent.com/89366675/192834231-b60b1372-ea82-4ba9-8262-3f90c85ed6e5.png)

So basically the settings for plugin are current inaccessible. I've tried disabling all my other plugins to see if that would fix it and it does not. 

### Expected behavior

The expected behavior would be to view and adjust the settings for the Double Click to Edit plugin

### To reproduce

1. Go to Discord Settings
2. Click Plugins in the BetterDiscord section
3. Click the settings cog for Double Click to Edit.
4. Receive error

### Screenshots

Screenshots already included in post.

### OS version

Windows 11

### Discord version

Stable

### BetterDiscord version

Stable 149549 (1e1ae6d) Host 1.0.9006 Windows 10 64-Bit (10.0.22000)

### Plugin version

9.3.5

**Comment by Farcrada** [comment]
Noted. Discord's had it's little swap that practically makes it impossible for us to find (and thus patch) modules.

I'll see what I can do.

**Comment by SeduSenpai** [comment]
The plugin's newest version is working for me on Windows 11 Home with Discord Stable.

**Comment by Farcrada** [comment]
Oop found the issue uploading fix now.
