### ISSUE TITLE
[Right Click Join] Broken by new Discord updates

### ISSUE THREAD

**Issue by Farcrada** [Farcrada/DiscordPlugins#113]
### Describe the bug

Broken by new Discord updates. This includes the new API change for Better Discord.

### Expected behavior

A working plugin

### OS version

Any

### Discord version

Any

### BetterDiscord version

>1.8.0

### Plugin version

Any

**Comment by The-original-Draco** [comment]
Hey, do you have any Idea hwo to fix the Problem with Right Click Join not working? 
If you need Help I would like to, but tbh I know nothing about coding on Discord Plugins and so on, so I'm not sure if I am somehow able to help, but as I like this Plugin and want to use it again, I'll try my best ;)

**Comment by Farcrada** [comment]
Thank you and be my guest. I haven't gotten to RCJ yet. Soon TM 😂

**Comment by Soulivan71** [comment]
Hi update ?

**Comment by Farcrada** [comment]
Yes sir!

It seems that certain functionality to protect a user from being banned for API spamming is no longer working from Discord itself. This means I'll need to make this myself with all the jank that can arise from it or I'll have to wait until we have a better opportunity.

I'll have to see what I can come up with.

**Comment by Soulivan71** [comment]
Okay

**Comment by DamsDev1** [comment]
Hi update ?

**Comment by Killua81** [comment]
hi update ?

**Comment by Farcrada** [comment]
After some time I've found the time to get to work on this. As far as I can test it works pretty well.

Let me know if you run into any issues.

**Comment by Soulivan71** [comment]
Thx  !

**Comment by Soulivan71** [comment]
Im still having issue : 
![image](https://github.com/Farcrada/DiscordPlugins/assets/36502190/874811d6-a1eb-4dae-a1b0-9c7b29aa3759)
I don't have the join call button

**Comment by Farcrada** [comment]
I see. That's unfortunate. I've found an additional issue where the button won't even show up at all.

I'll be taking a little longer to fix the button not showing up. In the mean time I have released a fix for the plugin crashing.
