### ISSUE TITLE
[DoubleClickToEdit] Double click reply function broke again

### ISSUE THREAD

**Issue by maenDisease** [Farcrada/DiscordPlugins#115]
### Describe the bug

Unable to double click to reply a message, issue began yesterday or the day before

### Expected behavior

To reply

### To reproduce

1. Enable replying
2. Double click a message

### Screenshots

![image](https://user-images.githubusercontent.com/90428263/196586609-ac54e831-9f57-47f8-8d59-749694a4bcb8.png)

### OS version

Windows 10

### Discord version

Canary

### BetterDiscord version

1.8.2

### Plugin version

9.4.1

**Comment by Farcrada** [comment]
Sigh... Discord, pls. On it.
