### ISSUE TITLE
[Hide Channels] Settings Modal Not Opening

### ISSUE THREAD

**Issue by Linkinlog** [Farcrada/DiscordPlugins#116]
### Describe the bug

The settings modal does not open, clicking the settings icon results in a error in the console saying `Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined`, it seems like this issue is related to `Hide-Channels/HideChannels.plugin.jsL128`

### Expected behavior

The settings modal to open 

### To reproduce

1. Open discord
2. Go to settings > plugins
3. Click the settings wheel for Hide Channels
4. Profit

### OS version

Windows 11

### Discord version

Stable

### BetterDiscord version

1.8.2

### Plugin version

2.2.5

**Comment by Farcrada** [comment]
Yup, thanks Discord. Volatile as always. 😂 

Thanks for reporting.
