### ISSUE TITLE
[DoubleClickToEdit] Double click reply function broke again

### ISSUE THREAD

**Issue by maenDisease** [Farcrada/DiscordPlugins#120]
### Describe the bug

Can't double click to reply

### Expected behavior

to reply

### To reproduce

1. enable reply setting
2. double click to reply

### Screenshots

![image](https://user-images.githubusercontent.com/90428263/201166096-27e73538-b0bb-4f24-8b60-57222149886e.png)

### OS version

Windows 10

### Discord version

Canary

### BetterDiscord version

1.8.2

### Plugin version

9.4.2

**Comment by Farcrada** [comment]
On it.

**Comment by Farcrada** [comment]
Lmao. The formatter entered a whitespace/newline which broke the search. I can't even. The settings as the switch item that got revamped I guess.

Uploading fix now.
