### ISSUE TITLE
Updates break the plugin

### ISSUE THREAD

**Issue by lejaju** [Farcrada/DiscordPlugins#122]
### Describe the bug

When hiding a channel with latest version of Discord Stable 161255 (cf8b6cb) this plugin hides the channels but user's own profile information moves into the main message box. 
![image](https://user-images.githubusercontent.com/78938062/204744547-8069a280-9e92-4e08-b7c7-44536894a663.png)

### Expected behavior

I expect my profile information to hide as well, just like it did before.

### To reproduce

1. Install this plugin on a latest Discord & Betterdiscord
2. Press Ctrl+H

### OS version

Windows 10

### Discord version

Stable

### BetterDiscord version

1.8.2

### Plugin version

2.2.6

**Comment by Farcrada** [comment]
Sigh. What the fuck is even this. 😂 
Discord Programming™

Investigating.
