### ISSUE TITLE
[Hide Channels] Adjustible animation

### ISSUE THREAD

**Issue by Saltssaumure** [Farcrada/DiscordPlugins#123]
### Is your request related to a problem? Please describe.

Animating width does a number on my poor laptop, so I've edited the plugin to remove the animation. It might be nice to have this as a setting for people who don't know how to edit.

### Describe the solution you'd like

Toggle on/off for the animation in plugin settings, or perhaps even further options for customising animation time.

**Comment by Farcrada** [comment]
I'll be honest. It's not your machine, Discord has TERRIBLE performance. And their uncontrolled programming and frankly ridiculous design choices make it even worse.

Nonetheless, I'll see what I can get cooking in terms of settings. What have you adjusted exactly?

**Comment by Saltssaumure** [comment]
Just got the ping, thanks for the speedy response and update! It works perfectly. You're right about Discord in general, but this one's at least partly on my laptop since it's not just Discord animations it has trouble with.
