### ISSUE TITLE
[Hide Channels] Doesn't work when viewing voice channels or streams

### ISSUE THREAD

**Issue by sarahnya** [Farcrada/DiscordPlugins#124]
### Describe the bug

The button to hide channels isn't visible in voice channels and the keyboard shortcut doesn't work either.

### Expected behavior

The button to be visible in the top left or for the shortcut to work.

### To reproduce

1. either join or open a voice channel
2. try whatever keybind you have set to hide channels or check for the hide channels button
3. nothing happens

### Screenshots

![image](https://user-images.githubusercontent.com/105610551/208492388-6f66d5d8-6e28-4f61-966a-52f80becec73.png)

### OS version

Linux (NixOS)

### Discord version

Stable (flatpak)

### BetterDiscord version

1.8.4

### Plugin version

2.2.8

**Comment by Farcrada** [comment]
Thanks for reporting; that's annoying.

Seems Discord fragmented their code even further. Short on time at the moment, will get fixed when I find the time.

**Comment by Farcrada** [comment]
Been a while. Currently investigating this issue.

Seems that a different `HeaderBar` is used. Have to find the right module to patch.

**Comment by sarahnya** [comment]
thank you!~
