### ISSUE TITLE
bypass delete confirmation

### ISSUE THREAD

**Issue by Farcrada** [Farcrada/DiscordPlugins#125]
Farcrada did this plug in, your "remove chat icons" plug in or any other use to have "bypass delete confirmation"?

_Originally posted by @iDeparture in https://github.com/Farcrada/DiscordPlugins/issues/24#issuecomment-1375700714_

**Comment by Farcrada** [comment]
What do you mean that? 

Confirmation to delete what?

**Comment by iDeparture** [comment]
> What do you mean by that?
> 
> Confirmation to delete what?

so in certain plugins have an option button next to them put in discord and some have additional  setting ie time stamps or just more to the plu in. i thought one of yours have bypass dealt confromati0on in the settings .

**Comment by iDeparture** [comment]
when you delete a message on discord it asks you are you sure and says pro tip holding ship just deletes it but there was an option in someons plug in i thought it was you and all you had to do wan enable it and the msgs would insta delete

**Comment by Farcrada** [comment]
That'd be DevilBro's plugin: Message Utilities. :)

**Comment by iDeparture** [comment]
damn coulda swore it was you ill have to check his i think i have that plug in thx <3
