### ISSUE TITLE
[DoubleClickToEdit] Settings open with error

### ISSUE THREAD

**Issue by maenDisease** [Farcrada/DiscordPlugins#127]
### Describe the bug

Settings don't load properly

### Expected behavior

Settings load properly

### To reproduce

1. Enable plugin
2. Open settings

### Screenshots

![image](https://user-images.githubusercontent.com/90428263/214687080-54837416-57cb-4c32-ad51-508cb1d17f40.png)

### OS version

Windows 10

### Discord version

Stable

### BetterDiscord version

1.8.4

### Plugin version

9.4.4

### Additional context

ZeresPluginLibrary had to be updated to fix settings not appearing for plugins that use it https://github.com/rauenzi/BDPluginLibrary/commit/f8f70ad003395ebb18bdd5e680df8a4185ead5bc

**Comment by Farcrada** [comment]
Investigating, can't fix right now. Please bear with me, will get to it when I have time.
