### ISSUE TITLE
[Hide Channels] Missing button in Stream view

### ISSUE THREAD

**Issue by KenLHua** [Farcrada/DiscordPlugins#128]
### Describe the bug

Hide Channel button doesn't appear when watching a stream

### Expected behavior

The hide channel button appears when watching a stream

### OS version

Windows 11

### Discord version

Stable

### BetterDiscord version

169617 (1ce88dc)

### Plugin version

2.2.8

**Comment by Farcrada** [comment]
Investigating, can't fix right now. Please bear with me.

**Comment by KenLHua** [comment]
All good. I took a look at the code. Seems the **patchTitleBar** function doesn't get triggered when opening up the stream window.

**Comment by Farcrada** [comment]
Duplicate of #124
