### ISSUE TITLE
[Double Click To Edit] Unable to update through topbar

### ISSUE THREAD

**Issue by cyrus01337** [Farcrada/DiscordPlugins#130]
### Describe the bug

In v9.4.4, when clicking the update button here it refuses to update.

### Expected behavior

The plugin should update to v9.4.5

### To reproduce

1. Install v9.4.4 [here](file:///home/cyrus/.var/app/com.discordapp.Discord/config/BetterDiscord/plugins/DoubleClickToEdit.plugin.js)
2. Attempt to update

### Screenshots

![Topbar](https://user-images.githubusercontent.com/63274991/221397390-adcad8e2-818d-4bc9-8790-f8cf802f5ffe.png)
![Console error](https://user-images.githubusercontent.com/63274991/221397489-0324b80c-eb7b-42a0-a619-53e6703ff531.png)

### OS version

Ubuntu 22.10

### Discord version

Stable

### BetterDiscord version

177026 (2a7afac)

### Plugin version

v9.4.4

### Additional context

This may be an issue on BetterDiscord's side as "Core" is at the latest version (`v1.8.4`, correct me if I'm wrong), I also made sure to reinstall BetterDiscord at the latest version to ensure it wasn't BetterDiscord.

I'm assuming the problem could be that the button has been renamed on BetterDiscord's side so the SDK(?) may need to be updated, just an afterthought.

**Comment by Farcrada** [comment]
That update banner makes use of Zere's pluginlibrary. Is that up to date? Get the latest version here: https://github.com/rauenzi/BDPluginLibrary

Does that resolve the issue?

**Comment by cyrus01337** [comment]
It does not, although according to rauenzi/BDPluginLibrary/177 this appears to be an ongoing issue for about a month now. Seems an update has been long overdue, though strangely enough this only started happening very recently after super reactions were added to Discord.

**Comment by cyrus01337** [comment]
Resolved, best guess is either installing the patched `betterdiscord.asar` from the BetterDiscord server (here's an [invite](https://discord.gg/0Tmfo5ZbORCRqbAd) and [jump link](https://discord.com/channels/86004744966914048/1031774670405501018)) or the recent commit to BetterDiscordAddons ([here](https://github.com/mwittrien/BetterDiscordAddons/commit/842b1eed9b62a80de6516ab68fa04c84d41cb0b2)).
