### ISSUE TITLE
[Hide Channels] Plugin Settings 'There was an unexpected error'

### ISSUE THREAD

**Issue by maenDisease** [Farcrada/DiscordPlugins#131]
### Describe the bug

New Discord update caused some plugins to break. The settings for Hide Channels broke

### Expected behavior

open plugin settings without error

### To reproduce

1. open the plugin's settings

### Screenshots

![image](https://user-images.githubusercontent.com/90428263/226084772-09afdb25-12e2-4505-ad22-0deb9368ae66.png)

### OS version

Windows 10

### Discord version

Canary

### BetterDiscord version

1.8.5

### Plugin version

2.2.9

**Comment by iDeparture** [comment]
ITS 

> ### Describe the bug
> New Discord update caused some plugins to break. The settings for Hide Channels broke
> 
> ### Expected behavior
> open plugin settings without error
> 
> ### To reproduce
> 1. open the plugin's settings
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/90428263/226084772-09afdb25-12e2-4505-ad22-0deb9368ae66.png)
> 
> ### OS version
> Windows 10
> 
> ### Discord version
> Canary
> 
> ### BetterDiscord version
> 1.8.5
> 
> ### Plugin version
> 2.2.9
> 
> ### Additional context
> _No response_

now the plug in isnt working at all and a bunch of others are buggy discord just updated

**Comment by Insan1ty0ne** [comment]
Still experiencing this issue as of April 9th 2023. Would really like to see this plugin get updated and fixed. It no longer works even on the release branch of Discord.

**Comment by Farcrada** [comment]
As far as I can tell the plugin works fine.

The settings however are another story. I've fixed this in the latest update.
