### ISSUE TITLE
[plugin name] Feature Request "Auto Join Setting-joins when member leaves";

### ISSUE THREAD

**Issue by iKnOoDaWaY** [Farcrada/DiscordPlugins#132]
### Is your request related to a problem? Please describe.

Feature Request - "Auto Join Setting-joins when member leaves";

### Describe the solution you'd like

Call channel use count, IF available slot join with 1-5 refresh;

Just an Idea, love the plug.

**Comment by Farcrada** [comment]
Apologize the late response.

What plugin are you referring to?

Regardless, this would not get through the guidelines. Mainly because you're trying to gain an advantage over others as per the connection limit plus automation. For that reason, be it the case or not, I'll not be making this.
