### ISSUE TITLE
Hide Channels: Disable Hide Animation Restores

### ISSUE THREAD

**Issue by duckworx** [Farcrada/DiscordPlugins#133]
### Describe the bug

Basically once you turn off the Hide Animation in the Plugin Settings it works till you restart discord and it restores to use the Hide Animation 

### Expected behavior

Once discord is restarted the Plugin should at least save the change

### OS version

Windows 11

### Discord version

Stable 199626

### BetterDiscord version

1.92

### Plugin version

Hide Channels v2.2.10 by Farcrada

**Comment by Farcrada** [comment]
Almost a year too late, but I fixed it.

Sorry.
