### ISSUE TITLE
[Double Click To Edit] Double Clicking your messages doesn't do anything.

### ISSUE THREAD

**Issue by Drflash55** [Farcrada/DiscordPlugins#136]
### Describe the bug

Trying to double click on your messages does not work.

### Expected behavior

Double clicking your messages should open up the edit box for you to edit the message.

### To reproduce

Double clicking on any of your messages.

### Screenshots

![image](https://github.com/Farcrada/DiscordPlugins/assets/13694448/71f9c7f5-66ff-4503-90db-b39dc9d194c6)
Discord spews out this error in the console.

### OS version

Windows 10

### Discord version

Stable

### BetterDiscord version

v1.9.3

### Plugin version

v9.4.5

### Additional context

I don't remember when this stopped working, but it was rather recent. A reload doesn't seem to fix the issue at all, or reloading the plugin.

**Comment by paraselen** [comment]
same issue

**Comment by pinetreemoonlight** [comment]
same issue here. made me realize how much i actually use this plugin lol.

**Comment by Deniz582** [comment]
after the Translator v2.5.7 plugin by DevilBro update the plugin no longer works

**Comment by DmitryOlenin** [comment]
[Double Click To Edit] stopped work :(
I have to use [MessageUtilities] after this situation.

**Comment by Farcrada** [comment]
I've uploaded the fix in the lastest version: https://github.com/Farcrada/DiscordPlugins/commit/d85d5503de8f5d7fdc61f22d8634dda904c6798e

Excuse my delay.
