### ISSUE TITLE
[Double Click To Edit] Triple/Quadruple Click to edit ?

### ISSUE THREAD

**Issue by OshidaBCF** [Farcrada/DiscordPlugins#138]
### Is your request related to a problem? Please describe.

the plugin itself is sooooo useful, but sometime i want to double click to select, even triple click to select the whole word

### Describe the solution you'd like

Could it be possible to select what key combination to use to edit, like CTRL + Double click or something ?

**Comment by Farcrada** [comment]
This is found in the settings tab. I've just now fixed the plugin because of a Discord update.

Does this satisfy your request?

**Comment by OshidaBCF** [comment]
oh i didn't noticed
Yup that should be perfect

Thks a lot

**Comment by OshidaBCF** [comment]
There is a slight issue, i want to use no modifier for editing, but shift double click to reply, and ctrl double click to copy, on other message it works, but on mine it always edit first so i can't copy.

i can just put a modifier for edit but i wonder if it's possible to change it so that pressing a modifier take priority ?

**Comment by Farcrada** [comment]
There's also an option to copy before editing, though that does enable for every double click and also only copies what is selected.

Does that work for you?

**Comment by OshidaBCF** [comment]
Ah that's how it work

I seee

Well perfect then
