### ISSUE TITLE
[Hide Chat Icons] Not working with current discord version

### ISSUE THREAD

**Issue by cosalich** [Farcrada/DiscordPlugins#140]
### Describe the bug

Plugin does not work and clicking settings results in:

"There was an unexpected Error. Click to open console for more details"

### Expected behavior

plugin works

### OS version

windows 11

### Discord version

Stable 232643

### BetterDiscord version

Cove v1.9.3

### Plugin version

v1.3.5

**Comment by Farcrada** [comment]
Noted, will investigate soon.

**Comment by RodasQ** [comment]
try disabling the transparency

**Comment by pikangie** [comment]
> try disabling the transparency

Thanks, this worked for me!

**Comment by Farcrada** [comment]
Is this still a current issue?

Haven't found any issues myself.

**Comment by hmx12-multi** [comment]
it fails to load on the latest version for me, and just brings up this error message (screenshot). 

![Screenshot_2024-06-19_07-44-39](https://github.com/Farcrada/DiscordPlugins/assets/83328530/d8ab5b05-b954-44da-8335-b9033a35a6e7)

not sure if me bringing this up is redundant in any way (it seems like a recent discord update broke 3rd party tools like BD and vencord), but i figured it couldn't hurt.

**Comment by Farcrada** [comment]
Closing as #153 could've fixed this. As well as the lack of replies.
