### ISSUE TITLE
[Double Click To Edit] double click to reply isn't working

### ISSUE THREAD

**Issue by BayKedi** [Farcrada/DiscordPlugins#144]
### Describe the bug

double click to reply isn't working

### Expected behavior

opens the replier

### To reproduce

1. open double click to edit
2. try to double click edit

### Screenshots

https://github.com/Farcrada/DiscordPlugins/assets/96437373/52db5673-e363-44ce-92d9-3b0ab8737609

### OS version

Windows 11 

### Discord version

Stable

### BetterDiscord version

Core v1.10.1

### Plugin version

v9.4.7

**Comment by walbjorn** [comment]
would also love to have this functionality back. thank you for all your work.

**Comment by flyingwolf79** [comment]
Just confirming this is a widespread bug as of the March 28th Discord update.

**Comment by AlAmantea** [comment]
COnfirmed bug. Double click to reply is non operational

**Comment by cityrobo** [comment]
Same issue here. Log output when double clicking message to reply: 
![image](https://github.com/Farcrada/DiscordPlugins/assets/84413175/dd141aaa-748b-4ade-9c3f-2f291aeb0ec1)

**Comment by cityrobo** [comment]
Expanding the log reveals an error in line 272 in the plugin, which is the call for the "replyToMessage" method I believe.
So I think it tries to reply but something changed with the late March discord update.

![image](https://github.com/Farcrada/DiscordPlugins/assets/84413175/b84d3950-a7c8-46d0-9d7f-86a4a3bb98a6)

![image](https://github.com/Farcrada/DiscordPlugins/assets/84413175/ed9fd705-9f13-447e-9c66-74c9927fa712)

![image](https://github.com/Farcrada/DiscordPlugins/assets/84413175/79a17843-289d-4cec-80b8-6f389f843521)

**Comment by BayKedi** [comment]
it got fixed

**Comment by StripedPuppy** [comment]
I'm having this issue as well. It just stopped out of nowhere the past few days for me.

I suppose I'll give reinstalling the plugin a shot.

**Comment by andrwmai** [comment]
Same here. This feature is crucial imo. Hope it gets fixed soon.

**Comment by Farcrada** [comment]
On it, apologies for the delays!

**Comment by flyingwolf79** [comment]
Much appreciated, this is free, no rush no worries. Thank you.

**Comment by Farcrada** [comment]
Submitted for review, let me know if there's any issues.

**Comment by andrwmai** [comment]
> Submitted for review, let me know if there's any issues.

Can confirm it's fixed. Thank you so much!

**Comment by flyingwolf79** [comment]
> Submitted for review, let me know if there's any issues.

Can confirm, it is working now.
