### ISSUE TITLE
Double click to edit not working

### ISSUE THREAD

**Issue by RipcordJack** [Farcrada/DiscordPlugins#147]
### Describe the bug

Double click to edit doesnt work after latest update to Better Discord

### Expected behavior

Double click should open option to edit message

### OS version

windows 11

### Discord version

Stable

### BetterDiscord version

1.10.2

### Plugin version

v9.4.8

**Comment by MJaroslav** [comment]
Same issue. I was run DC today and it's update itself and break DB installations and some plugins.
Details: OS ver: `Mint 21.3`, DC ver: `stable 303105 (1897d8a) Host 0.0.21 Build Override: N/A Linux 64-bit (5.15.0-112-generic)`, BD ver: `Core v1.10.2`, Plug ver: `v9.4.8`, and extra: open asar ver: `Nightly (4f264d8)`.

**Comment by Andy76swe** [comment]
same.. broke after latest Discord update with classes

**Comment by Halletz** [comment]
same

**Comment by Th3FiN4LSt4rT** [comment]
Same for me also

**Comment by AAUCrisp** [comment]
Me too

**Comment by TerraDK** [comment]
Same for me also after update.

**Comment by flamedance58** [comment]
Sameo!

No rush but would be great to see it updated.

**Comment by JonnyBro** [comment]
You can comment this line and plugin will load and work, but double click to reply will not work (I only use this plugin to edit myself): https://github.com/Farcrada/DiscordPlugins/blob/c70ba00ae3a95cd3fb5fe81a426cdde080736f38/Double-click-to-edit/DoubleClickToEdit.plugin.js#L50

**Comment by 1Phase1** [comment]
@JonnyBro Thanks a lot, this fixed it!

**Comment by StianNOR** [comment]
> You can comment this line and plugin will load and work, but double click to reply will not work (I only use this plugin to edit myself anyways):
> 
> https://github.com/Farcrada/DiscordPlugins/blob/c70ba00ae3a95cd3fb5fe81a426cdde080736f38/Double-click-to-edit/DoubleClickToEdit.plugin.js#L50
> 
> To comment this line place `//` before `this...` and save the file.

Thx that worked....

**Comment by AlAmantea** [comment]
Thanks for the quick fix! 
Now we need to figure out how to fix the reply to message function because I use that all the time!

**Comment by MJaroslav** [comment]
@AlAmantea 
> fix the reply

Try replace line suggested for comment (50) with next:
`this.replyToMessage = Webpack.getModule(m => m?.toString?.()?.replace('\n', '')?.search(/(channel:e,message:n,shouldMention:!)/) > -1, { searchExports: true })`

It's work for me but it's not good solution, I think. Explain: it's code from prev commit but with replaced regex.

**Comment by AlAmantea** [comment]
> @AlAmantea
> 
> > fix the reply
> 
> Try replace line suggested for comment (50) with next: `this.replyToMessage = Webpack.getModule(m => m?.toString?.()?.replace('\n', '')?.search(/(channel:e,message:n,shouldMention:!)/) > -1, { searchExports: true })`
> 
> It's work for me but it's not good solution, I think. Explain: it's code from prev commit but with replaced regex.

This worked perfectly! Thank you so much!

**Comment by Farcrada** [comment]
Should be all fixed now, just need to get it approved and you all should be getting the update!

Apologies for the delay
