### ISSUE TITLE
[double click to edit] Settings cant display, double click doesnt work

### ISSUE THREAD

**Issue by skkAYE** [Farcrada/DiscordPlugins#152]
### Describe the bug

Double click on my messages does nothing.

Also, the settings button of the plugin displays the following error message : "There was an unexpected Error. Click to open console for more details."
When i click, the message disappears and nothing happens.

### Expected behavior

Settings openable and plugin working

### Screenshots

![image](https://github.com/user-attachments/assets/17a73718-8f1b-47ae-96bc-d99fc1b95401)

### OS version

Windows 10 64-Bit (10.0.19045)

### Discord version

Stable 308381 (a65c916)

### BetterDiscord version

v1.10.2

### Plugin version

v9.4.8 (just tried with the latest)

### Additional context

I thought my theme could be the problem but i tried without it, same result.
I tried multiple times remove/re-add latest version of the plugin

**Comment by TheSidwysDrftr** [comment]
There is a solution by editing the code, but it seems like you are unable to edit at the moment.
Once you are able to find a solution to get to edit the code, here is a thread that shares what to edit to solve it. https://github.com/Farcrada/DiscordPlugins/issues/147

**Comment by Farcrada** [comment]
This seems to have been merged and fixed in #149

If these issues are still present please feel free to open and comment on this issue.
