### ISSUE TITLE
Hide Channels 2.2.12 Not Working After Update

### ISSUE THREAD

**Issue by 4verage** [Farcrada/DiscordPlugins#156]
### Describe the bug

After a recent Discord update and re-installing Better Discord, the Hide Channels plugin is no longer working correctly. The 'button' next to the channel list is present, when you click it the button properly rotates to represent a 'slide back out' option, but the channel list remains in place. I do not run any other plugins! I have Better Discord installed exclusively for this plugin and it is not working now. Do you mind checking on this for us? Thanks!

### Expected behavior

I expect the channel list to vanish (*poof*) when I click the icon and re-appear when I click the icon thereafter and so forth.

### To reproduce

1. Click the 'hide channels' button.
2. Observe the channels not hide.
3. Click the 'show channels' button.
4. Channels are still there.

### OS version

Windows 11 64-Bit

### Discord version

Stable 342968 (f8fde36)

### BetterDiscord version

Core v1.10.2

### Plugin version

2.2.12

### Additional context

Please help! Me love you long time!

**Comment by Shippou5** [comment]
I've managed to reproduce this bug

**Comment by Razwerkz** [comment]
I was able to reproduce this.

```
Discord stable 353815 (a932d4a) 
Windows 10 64-bit (10.0.19045)
BetterDiscord stable 1.11.0
Hide Channels v2.2.12
```

**Comment by nicola02nb** [comment]
Same issue to me

OS version
Windows 11 64-Bit

Discord version
Stable 354183 (e0813bf)

BetterDiscord version
Core v1.11.0

Plugin version
2.2.12

**Comment by fu-iq12** [comment]
Same, broke after an update

OS version
Windows 11 64-Bit

Discord version
Stable 354183 (e0813bf)

BetterDiscord version
Core v1.11.0

Plugin version
2.2.12

**Comment by Farcrada** [comment]
I'm having a look hope to get back to you guys soon.

**Comment by Farcrada** [comment]
Awaiting BD staff approval. 

Thanks @fu-iq12 for the fix, I thank you for this trip down CSS lane.

**Comment by 3werking** [comment]
I am currently experiencing this bug with the ClearVision theme. All plugins, themes and Discord itself are updated to their latest versions.

**Comment by aphirst** [comment]
![Image](https://github.com/user-attachments/assets/b6150e87-1b71-4635-93ac-b5b2e06aae06)

![Image](https://github.com/user-attachments/assets/e48b0b69-9391-4ccc-a283-816aade59df2)
Seems to be broken again by the new Discord UI updates.
