### ISSUE TITLE
Double-click-to-edit broken

### ISSUE THREAD

**Issue by Technetium1** [Farcrada/DiscordPlugins#19]
[Double-click-to-edit](https://github.com/Farcrada/DiscordPlugins/tree/master/Double-click-to-edit) is broken. According to the official plugin list the correct replacement that works is [MessageUtilities](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/MessageUtilities).

**Comment by Farcrada** [comment]
Let me have a look at what's going on.

**Comment by Farcrada** [comment]
Ah! Found the issue, Discord changed up message structure with the new Reply system. Uploading update, should hit your client in the next hour or so.

Could also replace it manually should you wish: https://github.com/Farcrada/DiscordPlugins/commit/0a5632241fc22d107c4f0b458b6336a4e2a6431b

**Comment by Farcrada** [comment]
A little addendum: https://github.com/Farcrada/DiscordPlugins/commit/4f2554fcdcee9f0db0e2a861500869f55393f65a

They changed it back again. GGs.
