### ISSUE TITLE
[Double click to edit] Doesnt load anymore

### ISSUE THREAD

**Issue by GeneralUltra758** [Farcrada/DiscordPlugins#25]
BD shows the following error
| Name  | Message  | Error  | 
|---|---|---|
|directDownload|Could not be constructed.|(0 , e.exports) is not a constructor|

BD Version info:

Stable 82117 (58a452e)
BD 1.0.0 (stable)
Host 0.0.309
Injector 0.6.0

**Comment by GeneralUltra758** [comment]
CORRECTION: meant directDownload not Double click to edit, Got the wrong repo by accident, tfw u have too many gihub tabs open to report issues, sorry

**Comment by Farcrada** [comment]
You're good!
Glad to see you're enjoying something I made and took the effort to report issues! ❤️
