### ISSUE TITLE
[Channel-Permissions] Tooltip stays stuck at top left (Update: briefly?)

### ISSUE THREAD

**Issue by Farcrada** [Farcrada/DiscordPlugins#28]
There is a weird occurrence where ~~when you collapse and/or mute a category~~ the tooltip gets bugged in the top left.

Only way to fix it is to ~~reload Discord~~ switch channels/guilds; if that proves fruitless reloading Discord works (`Ctrl + R`).

**Comment by YeetusBaboon** [comment]
![image](https://user-images.githubusercontent.com/83467783/123562395-375dbb80-d774-11eb-8b75-45a2fb6626b5.png)
Looks like this in the top left, seems to happen when you collapse all as soon as you click on a server. It will also duplicate the tooltip to look like this: 
![image](https://user-images.githubusercontent.com/83467783/123562416-552b2080-d774-11eb-9a49-7ca31f6050fb.png)
Unsure exactly how it was caused, but it seems ot only happen as soon as you click on a server.

**Comment by Farcrada** [comment]
With collapsed categories you hover as soon as you switch servers? Oh! Yes, I see it now. It doesn't even need to be collapsed either. Thank you, I didn't know this yet.

It only briefly shows. Do you share this experience? I can't seem to make it stick; which is arguably good?

**Comment by Farcrada** [comment]
There's a dev version and extra information here: https://github.com/Farcrada/DiscordPlugins/issues/52#issuecomment-912986765
that you can check out.

Soon to be released.

**Comment by Farcrada** [comment]
Fixed with merge: https://github.com/Farcrada/DiscordPlugins/pull/61
