### ISSUE TITLE
[BUG] [ChannelPermisions] Not Working for me

### ISSUE THREAD

**Issue by aitronssesin** [Farcrada/DiscordPlugins#31]
The puglin si not working for me when I hover a text channel or a voice channel.

**Comment by Farcrada** [comment]
- What version of Discord and BetterDiscord are you using?

- Do you have any other plugins running?

- Can you further elaborate what isn't working?

I am also trying to mitigate an issue I have with first time start-up situations. Which might fix your issue. Thank you for letting me know!

**Comment by aitronssesin** [comment]
I have the newest version of better discord

**Comment by aitronssesin** [comment]
Do you have any other plugins running?

Yes this:

WhoReactedv1.2.3by Jaime Filho

Shows the avatars of the users who reacted to a message.



VoiceUsersCounterv2.0.0by Strencher

Adds a count of users they're connected to a VoiceChannel. Customize the Color of the count in the SettingsPanel.



UserVolumeBoosterv1.0.0by QWERT

Allows you to set a user's volume above the normal 200%



TypingUsersAvatarsv1.0.2by QWERT

Shows avatars of typing users.



TypingIndicatorv0.5.1by l0c4lh057

Shows an indicator in the guild/channel list when someone is typing there



ThemeRepov2.2.6by DevilBro

Allows you to download all Themes from BD's Website within Discord


SuppressReplyMentionsv0.0.2by Strencher

Suppresses mentions from Replied messages and when replying to someone else.



StatusEverywherev0.4.9by Zerebos

Adds user status everywhere Discord doesn't.


StaffTagv1.4.5by DevilBro

Adds a Crown/Tag to Server Owners (or Admins/Management)




SpotifyControlsv1.1.7by DevilBro

Adds a Control Panel while listening to Spotify on a connected Account



ShowHiddenChannelsv3.0.0by DevilBro

Displays all hidden Channels, which can't be accessed due to Role Restrictions, this won't allow you to read them (impossible)




ServerSearchv0.1.5by Zerebos

Adds a button to search your servers. Search in place or in popout.


ServerHiderv6.2.0by DevilBro

Allows you to hide certain Servers in your Server List




ServerDetailsv1.0.6by DevilBro

Shows Server Details in the Server List Tooltip



SendLargeMessagesv1.6.8by DevilBro

Allows you to enter larger Messages, which will automatically split into several smaller Messages




SendEmbedsv2.1.0by Fraser Price

Allows you to send embeds


SendButtonv0.1.3by Zerebos

Adds a clickable send button.


SaveToReduxv2.3.4by Lighty

Allows you to save images, videos, profile icons, server icons, reactions, emotes, custom status emotes and stickers to any folder quickly, as well as install plugins from direct links.



RemoveBlockedMessagesv1.2.8by DevilBro

Removes blocked Messages/Users




ReadAllNotificationsButtonv1.6.8by DevilBro

Adds a Clear Button to the Server List and the Mentions Popout



QuickMentionv1.0.2by DevilBro

Adds a Mention Button to the Message Options Bar


QuickLastMessagev1.0.2by Bread

Quickly access your last message by pressing the down arrow


PluginRepov2.2.6by DevilBro

Allows you to download all Plugins from BD's Website within Discord


PermissionsViewerv0.1.17by Zerebos

Allows you to view a user's permissions. Thanks to Noodlebox for the idea!



NotificationSoundsv3.6.1by DevilBro

Allows you to replace the native Sounds with custom Sounds




NitroPerksv1.3.6by lemons

Unlock all screensharing modes, and use cross-server emotes & gif emotes, Discord wide! (You CANNOT upload 100MB files though. :/)



MessageLoggerV2v1.7.71by Lighty

Saves all deleted and purged messages, as well as all edit history and ghost pings. With highly configurable ignore options, and even restoring deleted messages after restarting Discord.



InAppNotificationsv1.0.10by Lighty

Show a notification in Discord when someone sends a message, just like on mobile.



GuildProfilev1.1.0by Jaime Filho

Adds a modal that can be opened via any guild menu and contains various information about the guild, such as its owner, creation date, joined date, your friends and blocked users who are in it, and much more.



GuildAndFriendRemovalAlertsv3.0.0by Metalloriff

Displays alerts when you are kicked/banned from a server, a server is deleted, and when a friend removes you.



GrammarCorrectv1.0.0by QWERT

Corrects your grammar mistakes just like Grammarly



GoogleTranslateOptionv2.2.7by DevilBro

Allows you to translate Messages and your outgoing Message within Discord




GlobalRepliesv1.0.0by QWERT

Allows you to reply to messages outside of the channel they were sent in.



GameActivityTogglev1.0.3by DevilBro

Adds a Quick-Toggle Game Activity Button




EmojiUtilitiesv0.0.9by Zerebos

Allows you to blacklist and favorite emojis.


EmojiStatisticsv2.9.8by DevilBro

Shows you an Overview of Emojis and Emoji Servers



EditUsersv4.3.2by DevilBro

Allows you to locally edit Users




CustomStatusPresetsv1.0.6by DevilBro

Allows you to save Custom Statuses as Quick Select




CreationDatev1.4.5by DevilBro

Displays the Creation Date of an Account in the UserPopout and UserModal




CompleteTimestampsv1.5.7by DevilBro

Replaces Timestamps with your own custom Timestamps




ChatAliasesv2.3.0by DevilBro

Allows you to configure your own Aliases/Commands




Channel Permissionsv3.5.1by Farcrada

Hover over channels to view their required permissions.


BugReportHelperv1.0.4by l0c4lh057

Makes it easier for you to report issues by adding a help button in some support channels (e.g. that on my server). Using that to report issues will (hopefully) give all the information needed for fixing the problem.



BlurNSFWv0.2.5by Zerebos

Blurs images in NSFW channels until you hover over it.



BiggerStreamPreviewv1.0.6by Marmota (Jaime Filho)

Adds a button in the context menu to see bigger stream previews.


BetterVolumev1.0.0by Zerthox

Set user volume values manually instead of using a limited slider.


BetterSearchPagev1.2.0by DevilBro

Adds some extra Controls to the Search Results Page




BetterRoleColorsv0.8.14by Zerebos

Adds server-based role colors to typing, voice, popouts, modals and more!



BetterImageViewerv1.5.10by Lighty

Move between images in the entire channel with arrow keys, image zoom enabled by clicking and holding, scroll wheel to zoom in and out, hold shift to change lens size. Image previews will look sharper no matter what scaling you have, and will take up as much space as possible.



BetterFriendListv1.3.3by DevilBro

Adds extra Controls to the Friends Page, for example sort by Name/Status, Search and All/Request/Blocked Amount




BetterFormattingReduxv2.3.11by Zerebos

Enables different types of formatting in standard Discord chat.



BetterFoldersv2.3.1by Zerthox

Add new functionality to server folders.



BetterBannedUsersv1.0.1by Strencher

Enhances the banned users page.



BadgesEverywherev1.7.4by DevilBro

Displays Badges (Nitro, Hypesquad, etc...) in the Chat/MemberList




AutoStartRichPresencev1.2.2by Mega_Mewthree

Auto starts Rich Presence with configurable settings. Required dependency: ZeresPluginLibrary My Discord server: https://nebula.mooo.info/discord-invite DM me @Lucario ☉ ∝ x²#7902 or create an issue at https://github.com/Mega-Mewthree/BetterDiscordPlugins for support.



AnimatedStatusv0.11.1by toluschr

Animate your Discord status



AccountDetailsPlusv0.1.10by Zerebos

Lets you view popout, nickname and more from your account panel at the bottom.



XenoLibv1.3.37by Lighty

Simple library to complement plugins with shared code without lowering performance. Also adds needed buttons to some plugins.



ZeresPluginLibraryv1.2.29by Zerebos

Gives other plugins utility functions and the ability to emulate v2.


BDFDBv1.7.1by DevilBro

Required Library for DevilBro's Plugins

**Comment by Farcrada** [comment]
T-that's a lot of plugins...

Uhm, ok, so first things first. 
- Restart Discord; still doesn't work?
- If you enable only `ZeresPluginLibrary` and `ChannelPermissions` and restart Discord, does it work then?

If it doesn't work with only `ZeresPluginLibrary` and `ChannelPermissions` enabled, then there is something else happening. In that case I ask you press `Ctrl + Shift + I` to open the `inspector` (you can go full-screen in Discord to maintain visibility), at the top on the "new" right window it should say `console`; open/click it. Wait for it to load (10 secs or so), click on a server, and press `Ctrl + R` to reload Discord.
- Are there any red texts that show up? (you can scroll up and down to check)
- If you hover over channels; do red texts show up?

These red texts are errors. With those I can more easily narrow down the problem. If you have any, could you click them (to open them, indicated by a little arrow at the top left of the red box), screenshot them entirely and put them here?

If it does work with just `ZeresPluginLibrary` and `ChannelPermissions` enabled, could you enable one plugin, switch server, test again and do this until it stops working. If it stops working note the plugin - you have just enabled which made it stop working - down (just the name is fine) and then keep it disabled and continue the search while switching servers and testing each time to see if there are other plugins.

For the plugins with which it doesn't work; do red texts in the `console` show up? Would you be so kind as to post those (as well)?

**Comment by Farcrada** [comment]
It seems https://github.com/Farcrada/DiscordPlugins/issues/33 is related to this.
