### ISSUE TITLE
[ChannelPermissions] external patch/`rerender`/`forceUpdate` of the channel list removes Event Listener

### ISSUE THREAD

**Issue by lolpowerluke** [Farcrada/DiscordPlugins#33]
popup stops showing when see list is enabled
1: spotifyControls
2: notificationSounds
3: pinDMs
4: serverFolders
Steps to reproduce the behaviour:
enable see list and channelPermissions

popup doesnt show up

**Comment by Farcrada** [comment]
If you press `Ctrl + Shift + I` and click `console` at the top right; are there any red blobs that show up (console errors)? Could you screenshot those and post them if they're there?

**Comment by lolpowerluke** [comment]
if I restart channelPermissions, the poup shows again, but once I change channel it stops showing, also, it doesnt give any errors

**Comment by Farcrada** [comment]
Yes! I found out what happens. Channel Permissions gets kicked out when the other plugins start. I'll have to find out a way to mitigate that issue without breaking it.

I'm on it!

**Comment by Farcrada** [comment]
Latest update should resolve this.
