### ISSUE TITLE
[VoiceChatMoveAll] Idea?

### ISSUE THREAD

**Issue by Eden333** [Farcrada/DiscordPlugins#35]
Hi,

I don't know where else I could have contacted you, but here I am.
I've seen you are pretty active recently for new Discord Plugins, and wanted to ask something.
"Lighty" made a "VoiceChatMoveAll" plugin once, but then decided to delete it and I never knew why.
I really liked the plugin and have been looking all over to find a replacement.
The Idea would be that you can move all members, in your own server into a different channel all at once, instead of having to pull them one by one.
So my question is: would you be able to construct something like that, or did the old one get deleted for a reason of compatibility or something?

Sincerly
Eden

**Comment by Farcrada** [comment]
That's a very good idea! Thank you, and I'll see what I can come up with.

**Comment by slow** [comment]
Great work, in case the plugin that @Farcrada made breaks, i have my own version of it which does the same thing but in a slight different way. Find it at: https://github.com/slow/better-discord-plugins

I don't mean to sound like a dickhead by commenting on this but i had seen this while searching for my own plugin, but incase it does break feel free to use the version above.
