### ISSUE TITLE
[Hide Chat Icons] Clicking a message group icon multiple times enlarges chatbox

### ISSUE THREAD

**Issue by Hate9** [Farcrada/DiscordPlugins#41]
**Describe the bug**
Upon clicking a message group icon (a DM, a server, a channel, etc) multiple times, the chatbox gains additional padding at the bottom.

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to a DM conversation you are having
2. Click on either the DM chat you're in or the Home button
3. Repeat at least 3 times
4. Observe

**Expected behaviour**

the chatbox to stay the same size

**Screenshots**
https://i.postimg.cc/Vv9CY0YG/chatbox.png

**Please complete the following information:**

 - OS: [e.g. Linux Manjaro 21.0.7 64-Bit]
 - Plugin version [e.g. 1.3.1]
 - Better Discord (BD) Version [e.g. 1.2.0]

**Additional context**

It appears that this is being caused by additional buttons being created with `class="undefined"`, within the `div` with `class="buttonsParent"`.

**Comment by Farcrada** [comment]
Thank you, will investigate.

**Comment by Farcrada** [comment]
This is from a different branch, but does this fix the issue?
I have a feeling the issue is in the way it checks for an existing button.

Dev version to try out: https://github.com/Farcrada/DiscordPlugins/blob/hci-dev/Hide-Chat-Icons/HideChatIcons.plugin.js

**Comment by Hate9** [comment]
Yeah, that one fixes the issue

**Comment by Farcrada** [comment]
Merging, thank you!
