### ISSUE TITLE
[HideChannels] Keybind to hide channels?

### ISSUE THREAD

**Issue by Alespren** [Farcrada/DiscordPlugins#43]
**Is your feature request related to a problem? Please describe.**
It's a bit annoying to have to use the mouse to hide channels, as the button is a bit out of the way.

**Describe the solution you'd like**
A keybind, set by the user, that will hide/show channels. It should function exactly the same as the button, just activated by a keypress instead. This way users can hide channels really quickly and without using the mouse.

**Additional context**
The keybind should be customizable by the user.

**Comment by Farcrada** [comment]
Great idea, I recognize myself in this issue/enhancement. On it!

**Comment by Farcrada** [comment]
Added this in the new update. Have fun!
