### ISSUE TITLE
[DoubleClick2Edit] Double clicking on a message to edit does not work

### ISSUE THREAD

**Issue by Drflash55** [Farcrada/DiscordPlugins#44]
**Describe the bug**

No longer works when you double click a message as of the latest Discord version.

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to any server/DM where you can edit a message.
2. Double clicking on it does nothing.

**Expected behaviour**

It should bring up the space where you can edit the message without having to right-click on it.

**System Information/Versions**

 - OS: Window 10 Home
 - Plugin Version: V9.2.0
 - BetterDiscord 1.2.0
 - Stable 90699 (baa844b)

**Additional context**

Double Click editing worked before Discord had an update. And now after the update, it breaks it entirely. Not even reloading the plugins solves the issue.

**Comment by Farcrada** [comment]
On it. Just got notified about Discord update as well.

**Comment by Farcrada** [comment]
I will first await this pull request before pushing updates live: https://github.com/BetterDiscord/BetterDiscord/pull/948

I have investigated and made a separate branch for those looking for an immediate update; found here: https://github.com/Farcrada/DiscordPlugins/blob/new-react-version/Double-click-to-edit/DoubleClickToEdit.plugin.js
