### ISSUE TITLE
[Hide Channels] Clicking Settings button in BD Plugins Menu causes Crash

### ISSUE THREAD

**Issue by Alespren** [Farcrada/DiscordPlugins#46]
**Describe the bug**

In the newest update, clicking the Settings button for the plugin causes an immediate Discord crash (It shows the "Well, this is awkward" screen). 

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to the Plugins section in User Settings
2. Click on the Settings button for the Hide Channels plugin
3. Crash occurs (Press: `[Ctrl+Shift+I]` to see an error from the console)

**Expected behaviour**

The settings for the plugin show up.

**Screenshots**

[Here's a gif of it happening](https://imgur.com/a/BT0WnIx)
[Error in console](https://imgur.com/a/5nK5zLv)

**Please complete the following information:**

 - OS: Windows 10 64bit
 - Plugin version: v1.2.0
 - Better Discord (BD) Version: 1.2.0

**Additional context**

This doesn't occur with any other plugins, at least that I have. I also removed all other plugins and the crash still occurred.

**Comment by Farcrada** [comment]
Damn. I'm on it!

The default shortcut is 'Ctrl + H' as long as you don't touch the settings button, does it still work?

**Comment by Farcrada** [comment]
The crash has been fixed, I'd love to hear if it's working as intended on your end.

**Comment by Alespren** [comment]
Yup, working perfectly now! Thanks
