### ISSUE TITLE
[Move-All-Voice-Users]not working

### ISSUE THREAD

**Issue by Eden333** [Farcrada/DiscordPlugins#47]
### Describe the bug

uhm.. I have it installed but the option to move all isnt showing, and yes I am in the same channel as the people I want to move.

### Expected behavior

Button missing

### Screenshots

![image](https://user-images.githubusercontent.com/18154402/127400201-31446fe2-c37f-4835-8996-d4a0ddebfb3e.png)

### Discord version

Stable 91492 (971f48d) BetterDiscord 1.2.1/1.2.0

### OS version

Windows 10 64-Bit (10.0.19042)

**Comment by Farcrada** [comment]
On it!

**Comment by Farcrada** [comment]
I cannot seem to replicate the issue; now I will agree that at most I've only been able to test with 5 people. I will try adn find out where the issue lies.

In the meantime does it still not work with only this plugin enabled? And if you slowly enable/add one plugin at a time?

**Comment by Eden333** [comment]
> I cannot seem to replicate the issue; now I will agree that at most I've only been able to test with 5 people. I will try adn find out where the issue lies.
> 
> In the meantime does it still not work with only this plugin enabled? And if you slowly enable/add one plugin at a time?

Will do!

**Comment by Farcrada** [comment]
Thank you for bringing this to my attention. I've found the issue and I'll see if I can make something of this.

**Comment by Farcrada** [comment]
This should be resolved in the next update. You should now be able to use `MentionChannels` along with `MoveAllVoiceUsers`.
