### ISSUE TITLE
[Double Click To Edit] error on startup

### ISSUE THREAD

**Issue by Hate9** [Farcrada/DiscordPlugins#48]
### Describe the bug

An error pops up on plugin load, saying "There is already a plugin with name DoubleClickToEdit", and the javascript below:
```
DoubleClickToEdit: There is already a plugin with name DoubleClickToEdit
    at Object.loadAddon (<anonymous>:4:192564)
    at Object.loadAddon (<anonymous>:4:229804)
    at Object.reloadAddon (<anonymous>:4:193371)
    at FSWatcher.<anonymous> (<anonymous>:4:190561)
```

### Expected behavior

no error

### To reproduce

1. update the plugin
2. restart

### Screenshots

![doubleclicktoedit](https://user-images.githubusercontent.com/4684153/127525167-0528a04e-c9a1-46a6-bcb3-6c7323f3f2cd.png)

### Discord version

Stable

### OS version

Linux Manjaro, Windows 10

**Comment by Farcrada** [comment]
I was worried that was going to happen. I tried.

I request you delete these files (if present) in your `Plugins` folder (found at the top in the plugin settings):
- `AutoScaleTextAreaIcons.plugin.js`
- `DoubleClickToEdit.plugin.js`

And install it again from: https://github.com/Farcrada/DiscordPlugins/blob/master/Double-click-to-edit/DoubleClickToEdit.plugin.js

My sincerest apologies.

**Comment by Drflash55** [comment]
So what exactly happened?

Did Double Click to Edit accidentally overwrite another plugin that should not have happened during the V9.2.1 update?

**Comment by Farcrada** [comment]
While exploring other oppertunities, I had edited the wrong source files which then made it onto GitHub.

In doing so it looked at the wrong place for an update. I have since fixed this; see: https://github.com/Farcrada/DiscordPlugins/tree/master/Auto-Scale-Text-Area-Icons

**Comment by Farcrada** [comment]
As I assume most people using this plugin will have seen this or fixed the issue; I will now be closing this.
