### ISSUE TITLE
[channel permissions] popup doesnt show

### ISSUE THREAD

**Issue by lolpowerluke** [Farcrada/DiscordPlugins#51]
### Describe the bug

popup doesn't show when hovering over channels
(not sure if its the plugin itself or a plugin incompatibility)

### Expected behavior

popup shows

### To reproduce

enable plugin and hover over a channel name

### Discord version

stable

### OS version

windows 10

**Comment by lolpowerluke** [comment]
not sure if its because of update or something else, but it works again

**Comment by Farcrada** [comment]
No worries! ❤️
