### ISSUE TITLE
[Channel-Permissions] Permission popup overlaps the stream preview

### ISSUE THREAD

**Issue by Jnss98b** [Farcrada/DiscordPlugins#52]
### Describe the bug

When someone's streaming, you effectively can't see the stream preview because the permission popup for the voice channel that user is connected to is on top of it

### Expected behavior

The permission popup should really just show up when you hover the voice channel's name, not when you hover over users in that voice channel

### Screenshots

![image](https://user-images.githubusercontent.com/24306400/128586116-7109df35-651e-48c2-9aa0-acf0181cc532.png)

### Discord version

Stable 92678

### OS version

Windows 10 21H1

**Comment by Farcrada** [comment]
I understand the issue. I'm looking into changing the way the tool tip is shown and maybe integrate the two. Thus far you can simply mouse over the preview and the permissions tool tip will disappear.

**Comment by lolpowerluke** [comment]
just an idea, but you could do it like this
![image](https://user-images.githubusercontent.com/47672899/128633011-f40dc220-478c-4525-8c76-d707644ccd1c.png)
strensher's channelDetails does it like that

**Comment by Farcrada** [comment]
Yup, that's what I'm aiming at.

**Comment by Farcrada** [comment]
For everyone that wants to help me improve before I replace it; I made a development build for those wanting to see how the new version looks/feels: https://github.com/Farcrada/DiscordPlugins/blob/Channel-Permissions-Dev/Channel-Permissions/ChannelPermissions.plugin.js

Current issues I see are:
- For voice channels it pops up a little too soon/violent.
- Categories don't have a pop-out (yet, requires some investigating; if at all possible).
- Colour difference between text and voice channels (but I perceive this as minor, Custom CSS if for that);

What I want to ask of you is a bit of feedback. What would you like to see changed/added?

**Comment by Farcrada** [comment]
Fixed in merge: https://github.com/Farcrada/DiscordPlugins/pull/61
