### ISSUE TITLE
[Channel Permissions] Add option for a delay before showing popup

### ISSUE THREAD

**Issue by J-E-Mc** [Farcrada/DiscordPlugins#54]
### Is your request related to a problem? Please describe.

The Channel Permissions popup opens immediately whenever I hover over a channel

### Describe the solution you'd like

I would like there to be a setting to add a delay before the popup opens up

### Describe alternatives you've considered

Maybe an option to add a keybind to open it up as well?

**Comment by Farcrada** [comment]
I agree. Very good idea.

I have a backlog, but I am on it.

**Comment by Farcrada** [comment]
I had gotten stuck on a revision of the plugin to further integrate it with Discord to remove some of the nuances it brought with it, apologies for not getting to you sooner: https://github.com/Farcrada/DiscordPlugins/issues/52#issuecomment-912986765

In your opinion, would that be an improvement already?
I'll look at a delay and hotkey option. Any special keys you have in mind?

**Comment by Farcrada** [comment]
Would update 4.0.0 satisfy your desires?

**Comment by Farcrada** [comment]
As mentioned: `Started on a delay functionality [...]`

Setting in settings menu coming soon, for now available in the `config` variable at the top under: `popoutDelay`.

**Comment by Farcrada** [comment]
Custom delay should now be added in the latest update. You can find it in the plugin settings.
