### ISSUE TITLE
[Hide Channels] Startup crash on latest Canary w/Powercord+BDCompat

### ISSUE THREAD

**Issue by MulverineX** [Farcrada/DiscordPlugins#57]
### Describe the bug

Causes a crash on startup with a [react error](https://reactjs.org/docs/error-decoder.html/?invariant=130&args[]=undefined&args[]=)

### Expected behavior

Not crash

### Discord version

Canary

### OS version

Windows 10

### Additional context

I went through the process of elimination to be sure it's your plugin causing the crash.

**Comment by Farcrada** [comment]
Does it say what line the error occurs on? Perhaps if you open the error (triangle on the top left of the red section)?

Something like this: 
![image](https://user-images.githubusercontent.com/8385001/132364559-d02d670c-3af4-440c-ab6b-d2486c93f25d.png)

In the mean time; I'll have a look at Canary with BetterDiscord.

**Comment by Farcrada** [comment]
I found that as soon as I use the patcher on the Headerbar module, it crashes. I would advise you to use a previous version of HideChannels until this is resolved.

**Comment by Farcrada** [comment]
I think, but I'm not sure, that the latest update might have fixed the issue. Would you mind checking it out?

**Comment by Trazel-Apeally** [comment]
Dunno if it'd help at all, but I've had similar start-up crashing issues for a bit not and was just able to pin-point that HideChannels was the culprit.

When disabled BD works fine, but as soon as I enable and Ctrl-R, it BD will crash consistently until the plugin is removed/disabled.

![image](https://user-images.githubusercontent.com/15951036/134497787-020d96dd-47b7-4ea1-9f0e-97905ed459ae.png)
![image](https://user-images.githubusercontent.com/15951036/134497845-fa69074c-b786-4f07-b156-2d0ba1a189d6.png)
![image](https://user-images.githubusercontent.com/15951036/134497867-8745e73d-79ab-44d3-b4e3-e8d5ee05756a.png)

**Comment by Trazel-Apeally** [comment]
And after Removing it and reloading:

![image](https://user-images.githubusercontent.com/15951036/134497945-04918f87-7691-4b51-a98e-347f3daf6305.png)
![image](https://user-images.githubusercontent.com/15951036/134497976-1ae3f224-db47-4595-b155-9a40297f2167.png)
![image](https://user-images.githubusercontent.com/15951036/134498040-ac16c9aa-add7-4065-ad55-70fdd6c375a2.png)

**Comment by Trazel-Apeally** [comment]
Oh and for context, I'm not on Canary or PTB. Hence me not being sure if my issue would be helpful for the other branches.

**Comment by Farcrada** [comment]
If you're not on Canary that means you're not on Powercord, what this current issue is about: https://powercord.dev/installation

I urge you to remove the plugin and install the fixed updated version: https://betterdiscord.app/plugin/Hide%20Channels

**Comment by Trazel-Apeally** [comment]
Ah, I did miss the Powercode big, my apologies, thanks for the heads up about the updated version <3

**Comment by Farcrada** [comment]
@MulverineX Is there a status update on this issue?

**Comment by Farcrada** [comment]
It has been several months and several updates later, if this is still an issue please feel free to re-open or open a different issue.
