### ISSUE TITLE
[HideChannels] Crash with HideChannels + DevilBro plugins

### ISSUE THREAD

**Issue by SmolAlli** [Farcrada/DiscordPlugins#63]
### Describe the bug

On the new update of HideChannels, if you are using any of DevilBro's plugins (mainly NotificationSounds and PinDMs from reports on the BetterDiscord discord), there is a crash. People are being sent to Discord's "Well this is awkward" page.

Quote from DevilBro (link to message on his server - https://discord.com/channels/410787888507256842/410787888507256844/888388212282761236): "Some of my plugins cause the gui to completely rerender to enable some changes, the rerender causes HideChannels to crash
The issue is still on HideChannels part because it doesnt properly check if props/children exists"

This has been occurring a lot, so thank you in advance! :)

### Expected behavior

HideChannels doesn't crash Discord when DevilBro's plugins are used.

### To reproduce

1. Have the most recent version of HideChannels installed
2. Have BDFDB and at least 1 of DB's plugins installed
3. Crash!

### OS version

All versions

### Discord version

All

### BetterDiscord version

All

### Plugin version

2.0.2

### Additional context

Has been occurring consistently for many users of your plugin + DB's plugins.

**Comment by Farcrada** [comment]
Roger. Thank you for reporting.

Should be fixed in PR: https://github.com/Farcrada/DiscordPlugins/pull/62
