### ISSUE TITLE
[Hide-Channels] Keybind doesnt work on My Linux

### ISSUE THREAD

**Issue by iMADi-ARCH** [Farcrada/DiscordPlugins#68]
### Describe the bug

The Keybind doesnt work on My Linux (Arch btw)
It also doesnt change sometimes.
![image](https://user-images.githubusercontent.com/61308761/136644784-3c732181-0e79-4314-bb9b-20c83791ba43.png)

### Expected behavior

The edited keybind should toggle open/close the channels-pane.

### To reproduce

1. Open Discord user settings
2. Select Plugins from the left pane
3. Click on settings icon of the Hide channels Plugin
4. Click on the keyboard icon from the popup
5. Press a key combination
6. Click on Done
7. Close the settings
8. try pressing the key combination.

### OS version

Linux 64-bit (Arch)

### Discord version

Stable

### BetterDiscord version

1.2.1

### Plugin version

2.0.5

**Comment by Farcrada** [comment]
Oop! Found the issue with reflecting new keybinds. Working and uploading a fix right now.

**Comment by Farcrada** [comment]
Does that also fix your keybind not working?

Are you using your keybind when you have Discord selected? Because it doesn't work without Discord being the active window, unfortunately.

I haven't been able to find the keybind module that handles global keybinds.

**Comment by iMADi-ARCH** [comment]
It didnt :(
Yeah, discord is the focused window when i am pressing that keybind.

**Comment by Farcrada** [comment]
Is it just that single keybind that doesn't work?
Do other keybinds work?
Does the console (`Ctrl + Shift + I`) show any errors when you press the keybind, maybe after you switch channels, or after a reload (`Ctrl + R`)?

Since I don't have the ability to open a Linux box I can't quite attempt a reproduction either.

**Comment by iMADi-ARCH** [comment]
I have tried several keybinds including Ctrl + B, Alt + X, Alt + Q. None of them work.
![image](https://user-images.githubusercontent.com/61308761/136700573-f677dc08-856f-483e-b480-977ac1a99b11.png)
This is the only BetterDiscrod error i am getting. No error with i press the keybind.

**Comment by iMADi-ARCH** [comment]
opening and closing with the button:
![image](https://user-images.githubusercontent.com/61308761/136704818-972ebfba-3253-47d7-a7f4-3f54862a7bea.png)

pressing my keybind (Ctrl + B) :
![image](https://user-images.githubusercontent.com/61308761/136704862-792b155a-2744-4260-b77c-abc9b2d94aba.png)

pressing Ctrl + H:
![image](https://user-images.githubusercontent.com/61308761/136704884-e57b14b1-b40a-42f7-8f79-6d903790fd9e.png)

editing keybind:
![image](https://user-images.githubusercontent.com/61308761/136704921-ca4d5de0-616d-427b-a855-5dddf5b6529c.png)

**Comment by iMADi-ARCH** [comment]
I edited `.config/BetterDiscord/plugins/HideChannels.config.json` to :
`{
    "keybind": [
        [
            0,
            17
        ],
        [
            0,
            72
        ]
    ]
}`
from:
`{
    "keybind": [
        [
            0,
            37
        ],
        [
            0,
            42
        ]
    ]
}`
and it works(after reloading discord) !

I think that it was not able to write the edited keybind to the config file for some reason.
Hope that helps.

**Comment by iMADi-ARCH** [comment]
![image](https://user-images.githubusercontent.com/61308761/136705588-389be1c3-1dfc-4348-a60c-c38be92536bd.png)
It shows this in the edit keybind popup
when actually, 17 is Ctrl and 72 is 'H'
I think the unicodes are messed up somehow

**Comment by Farcrada** [comment]
Hmm. That would indicate that the keybind reader doesn't differentiate. I'll see if I can work on this.

**Comment by Farcrada** [comment]
Let me know if this fixes the issue for you @iMADi-ARCH
