### ISSUE TITLE
Was Told HideChannels needs an update

### ISSUE THREAD

**Issue by cupcakewarp** [Farcrada/DiscordPlugins#71]
### Describe the bug

https://github.com/mwittrien/BetterDiscordAddons/issues/1170

### Expected behavior

a

### To reproduce

a

### Screenshots

a

### OS version

a

### Discord version

a

### BetterDiscord version

a

### Plugin version

a

### Additional context

a

**Comment by Farcrada** [comment]
Since you didn't bother to provide additional details I'm under the impression thatyou're on an outdated version.

Remove the plugin from your folder and download the latest version from: https://betterdiscord.app/plugin/Hide%20Channels

If the problem persists on version 2.0.6 feel free to return.

**Comment by thu2468** [comment]
So im also running into this issue. I am on 2.0.6. Discord crashes and i had to manually go into plugin folder and edit the file to ".off"
