### ISSUE TITLE
[Channel permissions] Doesn't work with channels with no threads

### ISSUE THREAD

**Issue by teisseire117** [Farcrada/DiscordPlugins#74]
### Describe the bug

When hovering a channel with the cursor, it shows the Topic and Allowed roles, only if the channel has active threads. Otherwise it doesn't show anything.

I made a .gif to show you :
![SO0iEUM](https://user-images.githubusercontent.com/43145883/139962464-04469e7b-7b71-4ac0-ab00-3e45c149e9b0.gif) 

### Expected behavior

Have it working even if the channel has no active threads.

### Screenshots

https://i.imgur.com/SO0iEUM.gif

### OS version

Windows 10 64-Bit (10.0.19042)

### Discord version

Stable 103341

### BetterDiscord version

BetterDiscord 1.2.4

### Plugin version

v4.0.5

**Comment by XxUnkn0wnxX** [comment]
```
Stable 103410 (c92cabc)
BetterDiscord 1.2.4
Host 0.0.264 OS X 10.15.7 (20.6.0)
```

Same issue @Farcrada however I don't think it's just related to no threads its Hit N miss really.
Here is video demo: https://www.dropbox.com/s/cekkffvsud3m963/ChannelPermissionsHover.mp4?dl=0

**Comment by Farcrada** [comment]
Noted. I am investigating.

Thank you both for the extensive report.
