### ISSUE TITLE
[Double click to edit] Works in video player

### ISSUE THREAD

**Issue by OshidaBCF** [Farcrada/DiscordPlugins#75]
### Describe the bug

When double clicking on the video player (fullscreen or not), it will "edit" the message.

### Expected behavior

It should not edit the message if you double click on the video

### To reproduce

1) find or post a video
2) double click on it

### OS version

Windows 10

### Discord version

Stable 105691

### BetterDiscord version

1.3.0

### Plugin version

9.2.2

**Comment by Farcrada** [comment]
Good catch! I'm on it.

**Comment by Farcrada** [comment]
Hmm. I can't seem to reproduce this.

What kind of video player are you using/clicking on? What is the host? YouTube, Vimeo, just straight MP4?

**Comment by OshidaBCF** [comment]
I didn't tested on others, it was the regular discord player, so straight mp4.

I'll test later with different players

**Comment by OshidaBCF** [comment]
tried my best to show it...

https://user-images.githubusercontent.com/61458287/144741154-cfb728fd-5bb5-4b02-9376-b186e1927fd6.mp4

**Comment by Farcrada** [comment]
Roger. Although, the MP4 (preview or not) don't support double click to fullscreen.

But I get the issue. I'll investigate.

**Comment by OshidaBCF** [comment]
> Although, the MP4 (preview or not) doesn't support double click to fullscreen.

yeah that's kinda the issue

limited brain see player and think "double click to fullscreen"
so i always get fooled....

**Comment by Farcrada** [comment]
I cannot seem to reproduce this as described. Any further help would be appreciated.

**Comment by Farcrada** [comment]
Sorry it took so long.
