### ISSUE TITLE
[HideChatIcons] BD-compat

### ISSUE THREAD

**Issue by lolpowerluke** [Farcrada/DiscordPlugins#77]
### Is your request related to a problem? Please describe.

HideChatIcons doesnt work with the BD-compat package for kernel

### Describe the solution you'd like

if possible, make it work there to

**Comment by Farcrada** [comment]
I'll see what I can do. Bd-compat is pretty outdated I believe though.

**Comment by lolpowerluke** [comment]
The one for kernel isn't tho?

**Comment by lolpowerluke** [comment]
Here's the link
https://github.com/strencher-kernel/bd-compat

**Comment by Farcrada** [comment]
Does this still not work with BDCompat on Kernel?

**Comment by lolpowerluke** [comment]
BD-compat is currently broken so I cant test this

**Comment by lolpowerluke** [comment]
Imma close this since I don't think bd-compat will be fixed anytime soon
