### ISSUE TITLE
Double Click To Edit broken after update

### ISSUE THREAD

**Issue by Masono03** [Farcrada/DiscordPlugins#78]
### Describe the bug

newest version of canary makes the plugin not work at all anymore

### Expected behavior

double clicking something to edit it

### To reproduce

1. start plugin on newest canary
2. try to double click and edit

### OS version

windows 10

### Discord version

Canary 110776 (3fad6a5)

### BetterDiscord version

BetterDiscord 1.3.0

### Plugin version

v9.2.2

**Comment by Farcrada** [comment]
Noted, we're in the middle of adjusting to the new changes.

**Comment by Farcrada** [comment]
It seems that this isn't the case for Stable, does Canary still have this issue?

**Comment by yrnmsk** [comment]
> It seems that this isn't the case for Stable, does Canary still have this issue?

it is the case for stable version now too, ive noticed it for almost a day or two now

**Comment by Zzeyy** [comment]
**This happens to me only if I try to edit an answer, not a normal message.**

**Comment by Farcrada** [comment]
Yup, my bad with replied messages! Fixed in new update: https://github.com/Farcrada/DiscordPlugins/commit/75254829b2148eb0abaac2922eddddf629c0a32e

**Comment by Farcrada** [comment]
> > It seems that this isn't the case for Stable, does Canary still have this issue?
> 
> it is the case for stable version now too, ive noticed it for almost a day or two now

I am still unable to replicate the issue on Canary or Stable. I recommend removing the plugin and downloading a fresh version.

**Comment by yrnmsk** [comment]
> I am still unable to replicate the issue on Canary or Stable. I recommend removing the plugin and downloading a fresh version.

yup, fixed for Stable as of rn with the latest update. thanks a lot
