### ISSUE TITLE
[Right Click Join] doesn't work after latest discord update

### ISSUE THREAD

**Issue by barbaduk** [Farcrada/DiscordPlugins#79]
### Describe the bug

there is just no button in right click menu

### Expected behavior

to work

### OS version

win 10

### Discord version

Stable 110451 (c233a73)

### BetterDiscord version

BetterDiscord 1.3.0

### Plugin version

1.2.1

**Comment by Farcrada** [comment]
The context menu's have been overhauled, I need some time to adjust to the changes.

**Comment by Farcrada** [comment]
Should be completely fixed now!

**Comment by barbaduk** [comment]
Doesn't show up in friends list (but does in chats and other places)
![ScreenX_2022 02](https://user-images.githubusercontent.com/41954202/151970394-cc8d6501-770b-491f-a5f9-b442745cc89e.gif)
