### ISSUE TITLE
[Right Click Join] Doesn't work from friends list

### ISSUE THREAD

**Issue by barbaduk** [Farcrada/DiscordPlugins#80]
Doesn't show up in friends list (but does in chats and other places)
![ScreenX_2022 02](https://user-images.githubusercontent.com/41954202/151970394-cc8d6501-770b-491f-a5f9-b442745cc89e.gif)

_Originally posted by @barbaduk in https://github.com/Farcrada/DiscordPlugins/issues/79#issuecomment-1026803309_

**Comment by Farcrada** [comment]
Noted! Good catch.
