### ISSUE TITLE
[plugin name] short descripton

### ISSUE THREAD

**Issue by Zzeyy** [Farcrada/DiscordPlugins#81]
### Describe the bug

I cannot double click to edit an asnwer, but I can double click and edit a normal message.

### Expected behavior

I should be able to edit all messages sent by me, right?

### To reproduce

1. Double click an answer
2. Stimulate your senses
3. Expect the bug to show up

### OS version

Windows 10

### Discord version

Stable

### BetterDiscord version

1.5.0

### Plugin version

v9.2.3

**Comment by Farcrada** [comment]
Fixed in: https://github.com/Farcrada/DiscordPlugins/commit/75254829b2148eb0abaac2922eddddf629c0a32e

My apologies!
