### ISSUE TITLE
[Right Click Join] Doesn't seem to work since Discord update

### ISSUE THREAD

**Issue by barbaduk** [Farcrada/DiscordPlugins#82]
### Describe the bug

Did i break something or another Discord update did?
Stable 113194 (8bfb811)
"Join" button doesn't show up **anywhere** 
Tried reinstalling BD and plugin

### Expected behavior

-

### OS version

Windows 10

### Discord version

Stable

### BetterDiscord version

1.5.0

### Plugin version

1.3.2

**Comment by Farcrada** [comment]
I am indeed disappointed by Discord. IT is out of my hands. We're having a hard time reaching the context menu's again because they've been wrapped inside a wrapper which is inside a wrapper.

See it as trying to get the inside of an onion without piercing the skin. It's proving difficult to say the least. I've noted and will update asap.

**Comment by Farcrada** [comment]
It's not pretty, and the first time it will probably not load (if it's a new user/fresh right click) and will require a second click, but we're getting there.

**Comment by barbaduk** [comment]
> It's not pretty, and the first time it will probably not load (if it's a new user/fresh right click) and will require a second click, but we're getting there.

@Farcrada Thank a lot!
btw i see almost every context menu plugin require second click now, Is this the way it is or can be fixed in future?

**Comment by Farcrada** [comment]
It has to do with the fact that we're unable to actually approach the context menu and feed it a React component of our own; at least: That's the case for me. 

React components possess the ability to update themselves live when a state changes, but the context menu only accepts certain preset components. I've tried making a custom version of it to try and retain that property but to no avail.

Other plugins might also rely on a dual pass, I don't know which context plugins you are mentioning. I have to wait until the dispatcher fetches a profile, which might either succeed and add the context option; or it might not. In that sense I try to delay that first pass, but that brings it's own complications with it.

So far we're getting there. It works decent enough, but we'll need to find a different way to patch the context menu if we're to integrate it properly.
