### ISSUE TITLE
[DoubleClickToEdit] Double click to reply

### ISSUE THREAD

**Issue by PixelyIon** [Farcrada/DiscordPlugins#83]
I've always found it fairly frustrating to have to go to the context menu to do a reply, the semantics of double clicking a message (that isn't from you) to reply works very well for this. A Discord internal module containing the function `replyToMessage` (which can be accessed using `BdApi.findModuleByProps("replyToMessage")`), allows replying to a function given the channel, message and event. It automatically handles holding shift to disable mention and not allowing mentions to webhooks or other invalid cases. 

The only challenge in calling it involves getting the channel object from the ID which is trivial due to Zeres Plugin Library providing access to `ChannelStore` via `ZeresPluginLibrary.DiscordModules.ChannelStore` where the `getChannel` method takes in the channel ID and returns the object.

The `replyToMessage` function can be invoked with the following code:
```js
(message, e) => {
    const MessageActions = BdApi.findModuleByProps("replyToMessage");
    const channel = ZeresPluginLibrary.DiscordModules.ChannelStore.getChannel(message.channel_id);
    MessageActions.replyToMessage(channel, message, e);
}
```

**Comment by Farcrada** [comment]
Should be live in the latest update. Make sure to check the plugin settings to enable it.

**Comment by PixelyIon** [comment]
Thanks, it works perfectly! :rocket:
