### ISSUE TITLE
[Hide Channels] No button in the Home

### ISSUE THREAD

**Issue by egeesin** [Farcrada/DiscordPlugins#85]
### Describe the bug

Just what title says. I'm not sure it's intended but the main functionality of this plugin still applies to the friend list in Home page before I hid the sidebar in any server page.

### Expected behavior

Button to show in Friends menu or to not affect the friend list

### To reproduce

1. Open "Home"
2. Resize the window wide enough to see every button on the top navigation.

### Screenshots

![image](https://user-images.githubusercontent.com/8004972/160919701-5e9287fd-960e-4530-b47a-035ff4118621.png)
I think there should be a toggle button on the left side of the "Friends" title.

### OS version

Windows 11

### Discord version

Stable

### BetterDiscord version

v1.5.2

### Plugin version

v2.1.1

**Comment by egeesin** [comment]
To be exact, if I open my friends DM page in Home, toggle button exists. So the issue happens only if I'm in "Friends" or "Nitro" page.

**Comment by Farcrada** [comment]
There is a shortcut button in settings; does the shortcut still work?

Sounds like either the headerbar changes drasticly or the window resizing starts merging the visibility and the use of a shortcut becomes necessairy.

**Comment by egeesin** [comment]
I'm able to toggle the sidebar with default Ctrl+H keybind even if there's no button in the page.

**Comment by Farcrada** [comment]
Found out what caused the issue, uploading new version asap.
