### ISSUE TITLE
[DoubleClickToEdit] Adding and removing react quickly enables edit/reply

### ISSUE THREAD

**Issue by Saltssaumure** [Farcrada/DiscordPlugins#88]
### Describe the bug

When a reaction is added and removed from a post quickly, that action is treated like a doubleclick on the message itself.

### Expected behavior

Clicking on reactions only adds/removes reaction, without any other actions taking place.

### To reproduce

1. Find post with existing reactions
2. Click a reaction twice to quickly add then remove a reaction.

### Screenshots

![Demo](https://i.imgur.com/ZAC02wS.gif)

### OS version

Win10

### Discord version

Stable

### BetterDiscord version

1.5.3

### Plugin version

v9.3.2

**Comment by Farcrada** [comment]
Should work as expected now!
