### ISSUE TITLE
[[Channel Permissions]] Channels ID was not translated to Channel name

### ISSUE THREAD

**Issue by Saud-97** [Farcrada/DiscordPlugins#90]
### Describe the bug

![image](https://user-images.githubusercontent.com/39028181/171051209-c7d8d8dc-4655-4a57-bd27-c05e664600be.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/39028181/171051254-661fdd1f-2573-4772-83e4-616866e28cda.png)

### OS version

win10

### Discord version

Stable

### BetterDiscord version

BetterDiscord 1.5.3

### Plugin version

v4.2.0by Farcrada

**Comment by Saud-97** [comment]
BTW thank you for the wonderful work on the hover delay. Really appreciate the hard work.

**Comment by Farcrada** [comment]
Thank you for using it!

Been meaning to get to it. I'll try to get it in the next update.

**Comment by Farcrada** [comment]
Fixed in https://github.com/Farcrada/DiscordPlugins/commit/feafb4a200a53c8a162c456c8c1fb5187b31ec17

Do get back to me if this (still) doesn't work.
