### ISSUE TITLE
[N/A] Plugin to hide members, exactly the same way hide channels works

### ISSUE THREAD

**Issue by robmonte** [Farcrada/DiscordPlugins#92]
### Is your request related to a problem? Please describe.

While the channel list can be completely hidden with a button press thanks to your Hide Channels plugin, the same isn't available for members.

### Describe the solution you'd like

It would be nice to have a button to hide the members panel in exactly the same way your hide channels plugin works. I know there's something _close_ offers mouseover expansion, but it still shows user icons. I'd like to have the icon at the top that completely hides it until I decide to view it again.

**Comment by Farcrada** [comment]
There is a button that pictures two persons that lets you toggle the memberslist.

**Comment by robmonte** [comment]
Wait a minute, is that... built into base Discord already? And I never noticed? 🤦‍♂️
