### ISSUE TITLE
[Double Click To Edit] Double click to reply isn't working

### ISSUE THREAD

**Issue by Egg-Roll** [Farcrada/DiscordPlugins#93]
### Describe the bug

When I double-click on another person's message that is not mine, it does open the thing like when you are replying to someone's message

### Expected behavior

I expected it to open up the "Replying to __" menu

### OS version

Windows 11

### Discord version

Stable

### BetterDiscord version

1.5.3

### Plugin version

v9.3.3

**Comment by Egg-Roll** [comment]
https://user-images.githubusercontent.com/89227698/177843234-8a4fd918-75cc-4fc4-b113-aa3e75e55a87.mp4

Umm a screenshot of what? I sent a video of me trying to double-click on a message to reply. I'm not sure if you can see it though.

**Comment by Egg-Roll** [comment]
I sent a video on github

Justin Do
________________________________

**Comment by Farcrada** [comment]
> It does open the thing when you reply to someone

And then you write:

> But it's not working.

The video clearly explains it's simply not working. Nothing pops up. In case you meant to toolbar at the top right of a message then that'd've been the confusion.

I'm working on a fix to bring compatibility back to compact mode. Apologies.

**Comment by Egg-Roll** [comment]
Oops sorry I meant to say "It **doesn't** open the thing when you reply to someone."

Thank you for the help

**Comment by Farcrada** [comment]
Found the bug. This happens when you switch from cozy (?) to compact mode (and vice versa). Because of this the document gets refreshed and the listener gets removed.

Quickest fix is reloading the page by `Ctrl+R`. Everything should work then.

Working on something to remedy this.

**Comment by Egg-Roll** [comment]
> Working on something to remedy this.

Alright then
