### ISSUE TITLE
[ChannelPermissions] Crashes Discord client on hovering channel

### ISSUE THREAD

**Issue by ItsCubeTime** [Farcrada/DiscordPlugins#95]
### Describe the bug

Microsoft Windows [Version 10.0.22000.739]
![image](https://user-images.githubusercontent.com/20190653/178334985-c9138a32-421b-4695-9c12-efe4f153b72d.png)

[Uploading debugToPostInBugReport.log…]()

https://user-images.githubusercontent.com/20190653/178335154-51229228-b400-43b2-8019-5000c39c335b.mp4

https://user-images.githubusercontent.com/20190653/178335232-d541f204-b912-4f20-ac27-07c27cf2ccf8.mp4

### Expected behavior

🤔

### OS version

-

### Discord version

-

### BetterDiscord version

-

### Plugin version

-

**Comment by Farcrada** [comment]
There's an update pending right at the top.

Does it still do this on the latest update?

**Comment by ItsCubeTime** [comment]
Ah sorry 😅 Ive gotten so used to seeing that blue bar at the top I havent bothered it for months. Yes indeed it works fine after updating.

Would it be possible for these plugins to just auto update?

**Comment by Farcrada** [comment]
Unfortunately not, but there is an update in the works that should streamline this.
